compressionLevel: mixed

enableGlobalCache: true

logFilters:
  - level: discard
    pattern: doesn't provide @babel/
  - level: discard
    pattern: "@docusaurus/core is listed by your project with version"
  - level: discard
    pattern: doesn't provide prop-types
  - level: discard
    pattern: doesn't provide prettier
  - level: discard
    pattern: doesn't provide hermes-eslint
  - level: discard
    pattern: doesn't provide react-native-macos
  - level: discard
    pattern: doesn't provide react-native-windows

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.17.0.cjs
