import { ListItemTokens } from '../../Theme/components/ListItemTokens'
import { rv } from '../../../rv'

export const listItem: ListItemTokens = {
    containerColor: (ds) => ds.sys.color.surfaceContainer,
    containerGap: rv(10),
    containerHeight: rv(56),
    containerOutlineColor: (ds) => ds.sys.color.outlineVariant,
    containerOutlineWidth: 1,
    containerPaddingHorizontal: rv(16),
    containerShape: (ds) => ds.sys.shape.extraSmall,
    headlineColor: (ds) => ds.sys.color.onSurface,
    headlineTypeScale: (ds) => ds.sys.typeScale.bodyMedium,
    iconColor: (ds) => ds.sys.color.onSurface,
    iconSize: rv(24),
    supportingTextColor: (ds) => ds.sys.color.onSurfaceVariant,
    supportingTextTypeScale: (ds) => ds.sys.typeScale.bodySmall,
    trailingSupportingTextColor: (ds) => ds.sys.color.onSurface,
    trailingSupportingTextTypeScale: (ds) => ds.sys.typeScale.titleSmall,
    disabledContainerColor: (ds) => ds.sys.color.onSurface,
    disabledContainerOpacity: (ds) => ds.sys.state.disabledContainerOpacity,
    disabledContainerOutlineColor: (ds) => ds.sys.color.onSurface,
    disabledContainerOutlineOpacity: (ds) => ds.sys.state.disabledContainerOpacity,
    disabledHeadlineColor: (ds) => ds.sys.color.onSurface,
    disabledHeadlineOpacity: (ds) => ds.sys.state.disabledOnContainerOpacity,
    disabledIconColor: (ds) => ds.sys.color.onSurface,
    disabledIconOpacity: (ds) => ds.sys.state.disabledOnContainerOpacity,
    disabledSupportingTextColor: (ds) => ds.sys.color.onSurface,
    disabledSupportingTextOpacity: (ds) => ds.sys.state.disabledOnContainerOpacity,
    disabledTrailingSupportingTextColor: (ds) => ds.sys.color.onSurface,
    disabledTrailingSupportingTextOpacity: (ds) => ds.sys.state.disabledOnContainerOpacity,
    pressedHeadlineColor: (ds) => ds.sys.color.onSurface,
    pressedIconColor: (ds) => ds.sys.color.onSurface,
    pressedStateLayerColor: (ds) => ds.sys.color.onSurface,
    pressedStateLayerOpacity: (ds) => ds.sys.state.pressedStateLayerOpacity,
    pressedSupportingTextColor: (ds) => ds.sys.color.onSurfaceVariant,
    pressedTrailingSupportingTextColor: (ds) => ds.sys.color.onSurface,
    selectedStateLayerColor: (ds) => ds.sys.color.onPrimaryContainer,
    selectedStateLayerOpacity: (ds) => ds.sys.state.pressedStateLayerOpacity,
}
