import { OutlinedTextInputTokens } from '../../Theme/components/OutlinedTextInputTokens'
import { rv } from '../../../rv'

export const outlinedTextInput: OutlinedTextInputTokens = {
    containerPaddingVertical: rv(9),
    containerPaddingHorizontal: rv(8),
    containerColor: (ds) => ds.sys.color.surfaceContainer,
    containerShape: (ds) => ds.sys.shape.large,
    containerGap: rv(16),
    outlineWidth: 1,
    outlineColor: (ds) => ds.sys.color.outlineVariant,
    leadingIconSize: rv(24),
    leadingIconColor: (ds) => ds.sys.color.onSurfaceVariant,
    trailingIconSize: rv(24),
    trailingIconColor: (ds) => ds.sys.color.onSurfaceVariant,
    caretColor: (ds) => ds.sys.color.primary,
    inputTextTypeScale: (ds) => ds.sys.typeScale.bodyMedium,
    inputTextColor: (ds) => ds.sys.color.onSurface,
    placeholderTextColor: (ds) => ds.sys.color.onSurface,
    placeholderOpacity: (ds) => ds.sys.state.disabledOnContainerOpacity,
    supportingTextTypeScale: (ds) => ds.sys.typeScale.labelSmall,
    supportingTextColor: (ds) => ds.sys.color.onSurfaceVariant,
    focusedOutlineColor: (ds) => ds.sys.color.primary,
    focusedOutlineWidth: 1,
    focusedContainerPaddingVertical: rv(9),
    focusedContainerPaddingHorizontal: rv(8),
    disabledContainerColor: (ds) => ds.sys.color.onSurface,
    disabledContainerOpacity: (ds) => ds.sys.state.disabledContainerOpacity,
    disabledLeadingIconColor: (ds) => ds.sys.color.onSurface,
    disabledLeadingIconOpacity: (ds) => ds.sys.state.disabledOnContainerOpacity,
    disabledTrailingIconColor: (ds) => ds.sys.color.onSurface,
    disabledTrailingIconOpacity: (ds) => ds.sys.state.disabledOnContainerOpacity,
    disabledOutlineColor: (ds) => ds.sys.color.onSurface,
    disabledOutlineOpacity: (ds) => ds.sys.state.disabledOnContainerOpacity,
    disabledInputTextColor: (ds) => ds.sys.color.onSurface,
    disabledInputTextOpacity: (ds) => ds.sys.state.disabledOnContainerOpacity,
    disabledSupportingTextColor: (ds) => ds.sys.color.onSurface,
    disabledSupportingTextOpacity: (ds) => ds.sys.state.disabledOnContainerOpacity,
    errorTrailingIconColor: (ds) => ds.sys.color.error,
    errorOutlineColor: (ds) => ds.sys.color.error,
    errorSupportingTextColor: (ds) => ds.sys.color.error,
}
